# Generated by Django 6.1.1 on 2026-09-04 00:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('classe', models.CharField(max_length=100)),
                ('type_cours', models.CharField(max_length=80)),
                ('statut', models.CharField(default='actif', max_length=20)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='core.site')),
            ],
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant_du', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(default='a_jour', max_length=20)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='echeances', to='eleves.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='ContactParent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=30)),
                ('lien', models.CharField(max_length=50)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='eleves.eleve')),
            ],
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['site', 'nom', 'prenom'], name='eleves_elev_site_id_879b34_idx'),
        ),
        migrations.AddIndex(
            model_name='echeance',
            index=models.Index(fields=['eleve', 'date_echeance'], name='eleves_eche_eleve_i_9628ce_idx'),
        ),
    ]
