# Generated by Django 6.1.1 on 2026-09-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
