# Generated by Django 6.1.1 on 2026-09-11 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_eleve_client_uuid'),
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeance',
            name='inscription_programme',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='echeance_programme', to='programmes.inscriptionprogramme'),
        ),
    ]
