# Generated by Django 6.1.1 on 2026-09-04 00:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_uuid', models.UUIDField(unique=True)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('mode_paiement', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True)),
                ('date_paiement', models.DateTimeField()),
                ('statut', models.CharField(default='valide', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('echeance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='eleves.echeance')),
                ('saisi_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_saisis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_action', models.CharField(default='annulation_paiement', max_length=50)),
                ('statut', models.CharField(default='en_attente', max_length=20)),
                ('motif', models.TextField()),
                ('commentaire', models.TextField(blank=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_soumises', to=settings.AUTH_USER_MODEL)),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_annulation', to='paiements.paiement')),
            ],
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['echeance', 'statut'], name='paiements_p_echeanc_53b4ad_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['date_paiement'], name='paiements_p_date_pa_cc74b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='demandevalidation',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'en_attente')), fields=('paiement',), name='une_annulation_en_attente_par_paiement'),
        ),
    ]
