# Generated by Django 6.1.1 on 2026-09-11 11:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_permission_gerer_echanges'),
        ('eleves', '0002_eleve_client_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('vacances', 'Vacances'), ('bac', 'Bac'), ('bepc', 'BEPC')], max_length=12)),
                ('nom', models.CharField(max_length=160)),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('ouvert', 'Ouvert'), ('cloture', 'Clôturé'), ('termine', 'Terminé'), ('archive', 'Archivé'), ('annule', 'Annulé')], default='brouillon', max_length=12)),
                ('matieres', models.JSONField(blank=True, default=list)),
                ('notes_bilan', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-annee_scolaire', 'nom'),
            },
        ),
        migrations.CreateModel(
            name='SessionProgramme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=160)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('capacite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('ouvert', 'Ouvert'), ('cloture', 'Clôturé'), ('termine', 'Terminé'), ('archive', 'Archivé'), ('annule', 'Annulé')], default='brouillon', max_length=12)),
                ('notes_bilan', models.TextField(blank=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='programmes.programme')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_programmes', to='core.site')),
            ],
            options={
                'ordering': ('-date_debut', 'intitule'),
            },
        ),
        migrations.CreateModel(
            name='GroupeProgramme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('niveau', models.CharField(max_length=120)),
                ('matiere', models.CharField(blank=True, max_length=120)),
                ('capacite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('complet', 'Complet'), ('cloture', 'Clôturé'), ('annule', 'Annulé')], default='ouvert', max_length=12)),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_programmes', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groupes', to='programmes.sessionprogramme')),
            ],
            options={
                'ordering': ('niveau', 'matiere'),
            },
        ),
        migrations.CreateModel(
            name='TarifProgramme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('debut_validite', models.DateField()),
                ('fin_validite', models.DateField(blank=True, null=True)),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='programmes.groupeprogramme')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='programmes.programme')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs_programmes', to='core.site')),
            ],
            options={
                'ordering': ('-debut_validite',),
            },
        ),
        migrations.CreateModel(
            name='InscriptionProgramme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tarif_fixe', models.PositiveIntegerField(blank=True, null=True)),
                ('remise', models.PositiveIntegerField(default=0)),
                ('motif_remise', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('brouillon_local', 'Brouillon local'), ('brouillon', 'Brouillon'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('motif_annulation', models.TextField(blank=True)),
                ('annulee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_programmes_annulees', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_programmes', to='eleves.eleve')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='programmes.groupeprogramme')),
            ],
            options={
                'indexes': [models.Index(fields=['eleve', 'statut'], name='programmes__eleve_i_e2d08f_idx'), models.Index(fields=['groupe', 'statut'], name='programmes__groupe__5c5434_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('statut', 'confirmee')), fields=('eleve', 'groupe'), name='inscription_groupe_confirmee_unique')],
            },
        ),
        migrations.CreateModel(
            name='SeanceProgramme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_seance', models.DateField()),
                ('nb_presents', models.PositiveIntegerField(blank=True, null=True)),
                ('nb_absents', models.PositiveIntegerField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='programmes.groupeprogramme')),
            ],
            options={
                'ordering': ('-date_seance',),
                'constraints': [models.UniqueConstraint(fields=('groupe', 'date_seance'), name='une_seance_programme_par_jour')],
            },
        ),
        migrations.AddIndex(
            model_name='sessionprogramme',
            index=models.Index(fields=['site', 'statut', 'date_debut'], name='programmes__site_id_c77c34_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupeprogramme',
            constraint=models.UniqueConstraint(fields=('session', 'niveau', 'matiere'), name='groupe_programme_unique'),
        ),
        migrations.AddIndex(
            model_name='tarifprogramme',
            index=models.Index(fields=['site', 'groupe', 'debut_validite'], name='programmes__site_id_350d41_idx'),
        ),
    ]
