# Generated by Django 6.1.1 on 2026-09-11 12:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_permissions_lot3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultatExamen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('observation', models.TextField(blank=True)),
                ('saisi_le', models.DateTimeField(auto_now=True)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resultat_examen', to='programmes.inscriptionprogramme')),
                ('saisi_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats_examens_saisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-saisi_le',),
            },
        ),
    ]
